source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

group :test, :development do
  gem 'sqlite3'
end

group :test do
  gem 'rspec-rails'
  gem 'shoulda-matchers'
end

group :production do
  gem 'pg'
end

gem 'redcarpet'
gem 'rouge'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'

gem "watu_table_builder", :require => "table_builder"